apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  eureka-url: "http://eureka-server:8761/eureka/"
  jwt-secret: "your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm-change-in-production"
  postgres-host: "postgresql"
  postgres-port: "5432"
  postgres-user: "postgres"

